version: '3.9'
services:
  asir-apache:
    image: php:7.4-apache
    container_name: asir-apache
    ports:
      - '8080:80'
    volumes:
      - ./html:/var/www/html/
      - confApache:/etc/apache2
volumes:
  confApache:
